web:
 props:
  uploadurl: "/upload"
  hostaddress: "http://localhost:8080"
upload:
  filepath:
        base: "/wordis/uploadfiles/"
        test: "/wordis/forupload/"
  filename:
        test: "testfile.xml"
  url: "/upload"
spring:
    profiles:
         active: "lambda"